version: '3.7'
services:
    githubsearch:
        container_name: githubsearch
        build: './githubsearch'
        command: start
        volumes:
            - ./githubsearch:/app
            - /app/node_modules
        ports:
            - '7887:3000'
        environment:
            - NODE_ENV=development
