# base image
FROM node:14.15.1 as build

WORKDIR /app

EXPOSE 3000

ENV PATH /app/node_modules/.bin:$PATH

# copiando as dependências e instalando
COPY package.json ./
RUN npm install --silent && npm install react-scripts@3.3.0 -g --silent

# Copiando os arquivos
COPY . ./

# Buildando a aplicação
RUN npm run build

#Criando o ambiente de produção
FROM nginx:1.20.1
#Copiando os arquivos de React para o ambiente nginx
WORKDIR /usr/share/nginx/html
# Removendo o arquivo de configuração padrão do nginx
RUN rm /etc/nginx/conf.d/default.conf
# Copiando os arquivos buildados
COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
